version: '3'

services:
  gitlab:
    image: ${IMAGE}
    restart: always
    hostname: ${HOSTNAME}
    container_name: gitlab
    #environment:
    #  GITLAB_OMNIBUS_CONFIG: |
    #    external_url 'http://gitlab.example.com:8929'
    #    gitlab_rails['gitlab_shell_ssh_port'] = 2224
    #ports:
    #  - '8929:8929'
    #  - '2224:22'
    ports:
      - '81:80'
      - '22:22'
      - '443:443'
    volumes:
      - './srv/gitlab/config:/etc/gitlab'
      - './srv/gitlab/logs:/var/log/gitlab'
      - './srv/gitlab/data:/var/opt/gitlab'

