version: '3'
services:
  web:
    image: 'gitlab/gitlab-ee:14.0.2-ee.0'
    restart: always
    hostname: '192.168.5.98'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://192.168.5.98'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '1022:22'
    volumes:
      - './data/config:/etc/gitlab'
      - './data/logs:/var/log/gitlab'
      - './data/data:/var/opt/gitlab'
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
